### ISSUE TITLE
Invalid cif file with no structures!

### ISSUE THREAD

**Issue by martinhp27** [caneparesearch/kMCpy#5]
Hi 
I am trying to run your kMCpy example for the nasicon system, but when I try to initiate the LCE, I get the error message "Invalid cif file with no structures!" 

Do you know why this happens? 
Also is it possible to use ASE objects as a starting point instead of a cif file? 

Best 
Martin

**Comment by dengzeyu** [comment]
Which example are you running? Have you tried `input_example/nasicon.ipynb`? The cif file is in `input_example/file_before_kmc/EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif`. You need to make sure you have pass the **full path** of your cif file to the code.

For your second question, cif file is mostly used standard crystallography file format. I'm pretty sure you can export the ASE to a cif file first as shown here https://wiki.fysik.dtu.dk/ase/_modules/ase/io/cif.html

**Comment by martinhp27** [comment]
Yes I tried that example and that cif file but I still get the error

**Comment by dengzeyu** [comment]
@martinhp27 We have fixed the bug in a commit 0cbbe5f2e9c6684d1e956130b26c3a47aeb36abd. Please try again.

**Comment by martinhp27** [comment]
@dengzeyu  thank you so much! It works :)
