### ISSUE TITLE
Problems Downloading kMCpy

### ISSUE THREAD

**Issue by TomatoTurtlez** [caneparesearch/kMCpy#8]
Hello,

I am interested in using your kMC package for my research project. My OS is Windows 11. Due to my organization's policy, I cannot use Conda to install the package/project. Is it possible to download the package through pip?

I have tried to download the GitHub repo and manually install the dependencies and virtual environment. But I keep running into the following error _ModuleNotFoundError: No module named 'kmcpy_' when trying to execute the wrapper _pythonw gui_wrapper.py_. I am not sure what I am doing wrong at the moment.

Thank you for your help.

**Comment by dengzeyu** [comment]
Hi sorry for my late reply.  I think you haven't installed successfully. Have you activated your virtual environment?

Please find the installation guide [here](https://github.com/caneparesearch/kMCpy?tab=readme-ov-file#with-no-gui-enabled-for-command-line-environment-running-on-server)
